services:

  database:
    image: postgres:15.5-alpine3.19
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - lan
    env_file:
      - .env

volumes:
  pg_data:

networks:
  lan:
    driver: bridge
